CREATE TABLE PRODUCT (
    BRAND_ID INT,
    START_DATE TIMESTAMP,
    END_DATE TIMESTAMP,
    PRICE_LIST INT,
    PRODUCT_ID BIGINT,
    PRIORITY INT,
    PRICE DECIMAL(10,2),
    CURR VARCHAR(3),
    PRIMARY KEY (PRODUCT_ID, PRICE_LIST)
);