openapi: "3.0.1"
info:
  title: Product API
  version: '1.0'
  description: API para gestionar productos
paths:
  /product:
    get:
      summary: Obtener productos
      description: Obtiene una lista de productos según los parámetros proporcionados.
      parameters:
        - in: query
          name: productId
          schema:
            type: integer
          description: ID del producto
          required: true
        - in: query
          name: brandId
          schema:
            type: integer
          description: ID de la marca
          required: true
        - in: query
          name: actualDate
          schema:
            type: string
            format: date-time
          description: Fecha actual (formato ISO 8601)
          required: true
      responses:
        '200':
          description: Productos encontrados
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponseDto'
        '204':
          description: No se encontraron productos
components:
  schemas:
    ProductRequestDto:
      type: object
      properties:
        productId:
          type: integer
          description: ID del producto
        brandId:
          type: integer
          description: ID de la marca
        actualDate:
          type: string
          format: date-time
          description: Fecha actual (formato ISO 8601)
      required:
        - productId
        - brandId
        - actualDate
    ProductResponseDto:
      type: object
      properties:
        rateApplied:
          type: integer
          description: Tarifa aplicada
        finalPrice:
          type: number
          format: double
          description: Precio final
        currency:
          type: string
          description: Moneda
        actualDate:
          type: string
          format: date-time
          description: Fecha actual (formato ISO 8601)
        productId:
          type: integer
          description: ID del producto
        brandId:
          type: integer
          description: ID de la marca
      required:
        - finalPrice
        - currency
        - actualDate
        - productId
        - brandId